### PR TITLE
A new feature to track who replied to channel messages ++

### PR DESCRIPTION
**Pull request by aaarghhh**
Added a functionality to list all users who replied to messages in chats, useful if you want to track who interact with message in channels.
It also dump replies of channel messages as your future plan. 

- Done some refactoring.
- Updated some libraries
- Added .gitignore to avoid to push sessions..

### TODO

- mapping reaction in groups, tracking who placed some reactions.
- add a flag to enable/disable the previous features

### CODE REVIEW

**Comment by jordanwildon** [comment]
This looks amazing! Would love to merge, but would you rather I wait until you've finished the todos?

**Comment by aaarghhh** [comment]
For the flag, I'll add it tonight. ;) 
For the reaction, I have to think a little because my goal was to track who reacted. On channel this feature isn't available because it seems that it's hidden by default so IMO the feature is viable only on chat,  I think this data could be integrated in the message report but I don't want to rewrite your work.

**Comment by jordanwildon** [comment]
Wonderful, I'll merge once you've done that. Thank you so much!

I've been taking some time to explore the same, but haven't made much progress on reactions. If you find some solutions for this (whether channels, or just groups), I'm totally open to collaborating on putting that together. I think it'd be a really beneficial feature :)

**Comment by aaarghhh** [comment]
Updated with the flag a fix on media directory, code cleaning with black.  
Updated the README with the new flag :smiley: 

Let me know what u think about.

**Review by jordanwildon — APPROVED** [review]

**Comment by jordanwildon** [comment]
Looks great, merged!

**Comment by aaarghhh** [comment]
Thank you a lot 🙂,  I'll start to watch the features missing in your TODO. I really enjoy Telepathy. If you want to plan the development reach me somewhere.

**Pull request merged**
